networks:
  ords-net:
    name: ords-net
    driver: bridge

volumes:
  oracle23aifree_data:
  ords-config:
  ollama-data:

services:
  oracle-23ai-free:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-23ai-free
    environment:
      - ORACLE_PWD=MeinSicheresPasswort123
      - NLS_LANG=AMERICAN_AMERICA.AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle23aifree_data:/opt/oracle/oradata
      - ./infra/oracle-db/sql-scripts/startup:/opt/oracle/scripts/startup:ro
    networks: [ords-net]

  ords:
    image: container-registry.oracle.com/database/ords:latest
    container_name: oracle-ords
    depends_on:
      - oracle-23ai-free
    environment:
      - DBHOST=oracle-23ai-free
      - DBPORT=1521
      - DBSERVICENAME=freepdb1
      - ORACLE_PWD=MeinSicheresPasswort123
    ports:
      - "8181:8080"
    volumes:
      - ords-config:/etc/ords/config
    networks: [ords-net]

  backend:
    build: ./backend_python
    image: backend:0.1
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - ORDS_BASE_URL=http://ords:8080/ords/projekt_lf12
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=mistral
      - ORDS_TIMEOUT=10
    depends_on:
      - ords
    networks: [ords-net]

  ollama:
    build: ./infra/ollama
    image: ollama-lf12:0.1
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_MODEL=mistral
    networks: [ords-net]

  frontend:
    build: ./frontend
    image: frontend:0.1
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks: [ords-net]
    read_only: true
    tmpfs:
      - /var/run
      - /var/cache/nginx
