-- Läuft EINMAL beim ersten Start (wenn das Dataverzeichnis leer ist)
-- Passe SCHEMA_NAME und PASSWORT an, falls du andere Namen nutzt.
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET CONTAINER = FREEPDB1;

-- Beispiel: Projektschema PROJEKT_LF12
CREATE USER PROJEKT_LF12 IDENTIFIED BY "MeinSicheresPasswort123"
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO PROJEKT_LF12;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO PROJEKT_LF12;
GRANT CREATE TRIGGER TO PROJEKT_LF12;
-- Optional, falls benötigt:
-- GRANT UNLIMITED TABLESPACE TO PROJEKT_LF12;
